# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d6a7d3948f24f254630d0d6f9e147152cc126c874fe974da93746ea4ff7389dc5716aeeb28b1249670ab21986702773c0e8289d01686d62041a480d80491d26

test:
  secret_key_base: aa6b55b7397c09338b23f970717eb6d7c2900fa180aa2e5b61f8f763a9991fc7ae7c961a18f9b2d164b12117756732265e1377865db02426cd38b33e080a7577

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
